### ISSUE TITLE
提示报错

### ISSUE THREAD

**Issue by tchangeme** [ifanrx/brick-layout#5]
VM2056:1 thirdScriptError
Cannot read property 'backgroundColor' of null; [Component] Property Observer Error @ plugin-private://wx3c042630f3cdc175/components/brickLayout/brickLayout#observer
TypeError: Cannot read property 'backgroundColor' of null
    at c.observer (http://127.0.0.1:19206/appservice/__onlineplugin__/wx3c042630f3cdc175/0.1.1/appservice.js:1275:451)
    at Function.o.safeCallback (http://127.0.0.1:19206/appservice/__dev__/WAService.js:15:2311)
    at i.<anonymous> (http://127.0.0.1:19206/appservice/__dev__/WAService.js:16:2495)
    at d (http://127.0.0.1:19206/appservice/__dev__/WAService.js:15:11899)
    at a.doUpdates (http://127.0.0.1:19206/appservice/__dev__/WAService.js:15:13111)
    at r.applyProperties (http://127.0.0.1:19206/appservice/__dev__/WAService.js:18:1425)
    at e.value (http://127.0.0.1:19206/appservice/__dev__/WAService.js:17:26120)
    at http://127.0.0.1:19206/appservice/__dev__/WAService.js:17:26192
    at Array.forEach (<anonymous>)
    at e.value (http://127.0.0.1:19206/appservice/__dev__/WAService.js:17:26164)

**Comment by tchangeme** [comment]
注释掉这句代码后问题解决：//var plugin = requirePlugin("myPlugin")

**Comment by heshiyou** [comment]
请提供使用 plugin 的版本以及调试基础库，以便我们定位问题

**Comment by tchangeme** [comment]
调试基础库是 2.0.4 ；
plugin 的版本为：
  "plugins": {
    "brickLayout": {
      "version": "0.1.1",
      "provider": "wx3c042630f3cdc175"
    }
另外这个版本是在微信平台上能搜到的唯一的一个版本；

**Comment by csm0522** [comment]
fixed , please use v 0.2 ，有任何问题欢迎重新 reopen this issue.
